### ISSUE TITLE
Can you provide the docker build command for the docker images

### ISSUE THREAD

**Issue by TokenTip** [QPod/docker-images#39]
I was hoping to add Pytorch and remove some items to make my image a little smaller. Can you share your build command.

**Comment by haobibo** [comment]
Thank you for your interests @TokenTip ! And sorry for the late reply.

The build command are actually in the `.travis.yml` file in each job - those `build_image_squash` commands. Basically, you can build the docker images (step by step) by running:
1. Using linux/macOS shell to define a shell function:
```bash
build_image_squash() { TAG=$1; FILE=$2; shift 2; docker build --squash --force-rm=true -t "qpod/qpod:$TAG" -f "$FILE" "$@" "$(dirname $FILE)"; }
```

2. Build Image stage by stage:

2.1  The base stage
```
build_image_squash base "docker_base/Dockerfile"
```

2.2 The base-cuda stage (only when you need cuda):
```bash
build_image_squash base-cuda "docker_base/cuda10.1.Dockerfile" \
  --build-arg "repository=qpod/qpod:base"
```

2.3 The jupyter stage (change `qpod/qpod:base` to `qpod/qpod:base-cuda` if you are building cuda image)
```bash
build_image_squash "jupyter-mini" "docker_jpy/Dockerfile" \
  --build-arg "repository=qpod/qpod:base" \
  --build-arg "ARG_EXTEND_JUPYTER=false" \
  --build-arg "ARG_NODEJS=false" \
  --build-arg "ARG_LATEX_BASE=false" \
  --build-arg "ARG_LATEX_CJK=false"
```

2.4 Build py-std stage (In this step you can add pytorch in the `docker_template/work/install_list_PY_cv.pip` or other files, modify the build-arg based on your needs):
```bash
docker build -t qpod/qpod:py-std -f ./docker_template/Dockerfile ./docker_template \
  --build-arg "repository=qpod/qpod:jupyter-mini" \
  --build-arg "base=jupyter-std" \
  --build-arg "ARG_MKL=true" \
  --build-arg "ARG_PY_DATABASE=false" \
  --build-arg "ARG_PY_DATASCIENCE=true" \
  --build-arg "ARG_PY_NLP=true" \
  --build-arg "ARG_PY_CV=true" \
  --build-arg "ARG_PY_BIOINFO=false"
```

Then, you will have several Docker images, among those, the `qpod/qpod:py-std` will be the one you want.

I *haven't* tested the scripts above, but they should work with minor modification.

Looking forward to get your feedback!
