### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by jml06** [QPod/docker-images#41]
Hello,
   First thanks for this huge work ! I installed everything following you webpage and everything works, actually on a Ubuntu-18.04.04 LTS server VM. Anyway i haven't understood well how works authentication. As we plan to use it in a multi-user environment, and probably on a CentOS 7;x with GPUs, i would like to know if it's possible to use PAM, which is the default authentication method for most of linux ?
Best Regards,
JM

**Comment by haobibo** [comment]
@jml06  Thank you for your interest!

This project now just serves as a container for a single user.
For multi-user use cases, please use the JupyterHub: https://jupyterhub.readthedocs.io/en/stable/

I've already tested it with GPU server and things work well!
Please try the Docker spawner ( https://github.com/jupyterhub/dockerspawner ) and provide your feedback here.

**Comment by jml06** [comment]
Hello,
Our env is:
- FreeBSD ZFS over NFS Kerberos HomeDIr server
- FreeIPA for Kerberos users and services managment
- A VM with Ubuntu 18.04.04LTS for jupyterHub tests configured with AutoFS / Kerberos Authentication. ON this one we try to run QPod on a multiuser basis. What works:

c.JupyterHub.spawner_class = 'dockerspawner.SystemUserSpawner'
c.DockerSpawner.remove_containers = True
c.DockerSpawner.image = 'jupyter/scipy-notebook:latest'
We have access to the UserDir who is connected.

But if we change to :
c.DockerSpawner.image = 'qpod/qpod:full'

It leads to these errors in syslog:
May  6 10:35:01 ljad70 jupyterhub[14415]: **ERROR:asyncio**:Task exception was never retrieved
May  6 10:35:01 ljad70 jupyterhub[14415]: future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /opt/jupyterhub/lib/python3.7/site-packages/jupyterhub/handlers/base.py:741> exception=HTTPError()>
May  6 10:35:01 ljad70 jupyterhub[14415]: Traceback (most recent call last):
May  6 10:35:01 ljad70 jupyterhub[14415]:   File "/opt/jupyterhub/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 939, in spawn_single_user
May  6 10:35:01 ljad70 jupyterhub[14415]:     timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
May  6 10:35:01 ljad70 jupyterhub[14415]: tornado.util.TimeoutError: Timeout
May  6 10:35:01 ljad70 jupyterhub[14415]: During handling of the above exception, another exception occurred:
May  6 10:35:01 ljad70 jupyterhub[14415]: Traceback (most recent call last):
May  6 10:35:01 ljad70 jupyterhub[14415]:   File "/opt/jupyterhub/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 972, in spawn_single_user
May  6 10:35:01 ljad70 jupyterhub[14415]:     % (status, spawner._log_name),
May  6 10:35:01 ljad70 jupyterhub[14415]: tornado.web.HTTPError: **HTTP 500: Internal Server Error (Spawner failed to start** [status=ExitCode=1, Error='', FinishedAt=2020-05-06T08:34:52.778451224Z]. The logs for jml may contain details.)
root@ljad70:/opt/jupyterhub/etc/jupyterhub# 


If using instead this config:
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.DockerSpawner.remove_containers = True
c.DockerSpawner.image = 'qpod/qpod:full'
The QPod Stuff load, but as root user, not connected one

**Comment by haobibo** [comment]
I wonder if the bug you encountered has resolved, just found that jhub recommends dockerspawner.DockerSpawner by default: https://jhubdocs.readthedocs.io/en/latest/dockerspawner/README.html#choose-a-spawner

BTW, I also found jhub supports using Kerberos for auth support: https://jupyterhub-kerberosauthenticator.readthedocs.io/en/latest/

So I wonder if using this authenticator supports your use cases better.
